#!/bin/bash --

if [ $(whoami) != root ]; then
  echo "Please run this script as root or using sudo"
  exit
fi

aptitude install zenity curl
mkdir cb-steam && cd cb-steam
mkdir /usr/lib/steam

wget http://media.steampowered.com/client/installer/steam.deb
sha1sum -c <<< "f71400e63a5e3746c09b7c291d47244667a1b169  steam.deb" && \
dpkg -X steam.deb cb-steam && dpkg -e steam.deb cb-steam/DEBIAN
sed -i 's/2.15/2.13/g' steam/DEBIAN/control
dpkg -b cb-steam cb-steam.deb || exit

dpkg -i cb-steam.deb
rm -f /etc/apt/sources.list.d/steam*

if [ $(uname -m) == i686 ] || [ $(uname -m) == i486 ]; then
  wget http://security.ubuntu.com/ubuntu/pool/main/e/eglibc/libc6_2.15-0ubuntu10.5_i386.deb
  sha1sum -c <<< "d45fdd5c82d1ffed1ba63a394563243637ce1b97  libc6_2.15-0ubuntu10.5_i386.deb" && \
  dpkg -X libc6_2.15-0ubuntu10.5_i386.deb libc6_2.15
  cp -r libc6_2.15/lib/* /usr/lib/steam || exit
  
  cat > /usr/bin/cb-steam <<EOF
#!/bin/bash
LD_LIBRARY_PATH=/usr/lib/steam/i386-linux-gnu:/usr/lib /usr/games/steam "$@"
EOF
  
else
  wget http://security.ubuntu.com/ubuntu/pool/main/e/eglibc/libc6_2.15-0ubuntu10.5_amd64.deb
  sha1sum -c <<< "ae1698a337689109582a1f318b641f4d3bb55282  libc6_2.15-0ubuntu10.5_amd64.deb" && \
  dpkg -X libc6_2.15-0ubuntu10.5_amd64.deb libc6_2.15
  cp -r libc6_2.15/lib/* /usr/lib/steam || exit
  
  cat > /usr/bin/cb-steam <<EOF
#!/bin/bash
LD_LIBRARY_PATH=/usr/lib/steam/x86_64-linux-gnu:/usr/lib /usr/games/steam "$@"
EOF
  
fi

chmod a+x /usr/bin/cb-steam
rm -r ../cb-steam
