#!/bin/bash

root=""
if [ $(id -u) != 0 ]; then
	if sudo -l >/dev/null 2>&1; then
		root="sudo sh -c"
	else
		root="su root -c"
	fi
fi

function install() {
$root "apt-get install cups cups-pdf printer-driver-hpijs \
	|| exit 1 \
	; adduser $(grep 1000 /etc/passwd | cut -d':' -f1) lpadmin \
	; cat > /usr/share/applications/cupsconfig.desktop <<EOF
[Desktop Entry]
Name=Printer configuration
Comment=Configure CUPS
Exec=x-www-browser http://127.0.0.1:631
Icon=printer
Terminal=false
Type=Application
StartupNotify=true
Categories=GTK;Settings;DesktopSettings;
EOF"
}

echo "Install CUPS (Common Unix Printing System)"
echo "Press \"y\" to install CUPS, or any key to abort"
read -r -n1 a
echo ""

case "$a" in
	[yY])
		install
		;;
	*)
		exit
		;;
esac

if [ $? = 0 ]; then
	echo "Press \"y\" to configure CUPS, or any key to abort"
	read -r -n1 b
fi

case "$b" in
	[yY])
		x-www-browser http://localhost:631
		;;
	*)
		exit
		;;
esac
