#!/bin/bash
# nurse - Automatically patch Debian packages

if (( $UID == 0 )); then
	echo "Don't build as root, handsome."
	exit 1
fi

pkg=gtk+3.0
pool=$pkg | cut -c 1
ver=3.12.2
rel=1
dist=unstable
prep=(quilt debian-archive-keyring devscripts curl)
source=http://ftp.de.debian.org/debian/pool/main/$pool/$pkg_$ver-$rel.dsc
patch="https://bugs.debian.org/cgi-bin/bugreport.cgi?msg=25;filename=gtk3_disable_csd_envvar.patch;att=1;bug=744249"

if ! dpkg -l $prep &>/dev/null; then
	sudo apt-get install $prep
	sudo apt-get build-dep $pkg
fi

prepare() {
	dget $source || exit 1
	pushd "$pkgname-$pkgver"
	test -d debian/patches || mkdir -p debian/patches
	pushd debian/patches
	curl -Lo meds.patch "$patch"
	quilt import meds.patch
	popd && quilt push -a
}

build() {	
	dch --local +bbq --distribution $dist "Little GNOMEs in space."
	dpkg-buildpackage -us -uc
}

clean() {
	tac /var/log/apt/history.log | grep -m1 Install \
	| sed "s|\(([^)]*)\)||g;s|,\s||g;s|Install:||" \
	| xargs sudo apt-get purge
}

prepare && build && \
read -r -p "Remove build dependencies? [y/n]" OPTION
case $OPTION in
	[yY])
		clean
		;;
	[nN])
		exit
		;;
esac
