#!/bin/bash
# nurse - Automatically patch Debian packages

### BEGIN PKG INFO
pkg=dwm
ver=6.0
rel=6
dist=unstable
pool=$(echo $pkg | cut -c 1)
source="http://ftp.de.debian.org/debian/pool/main/$pool/$pkg/${pkg}_$ver-$rel.dsc"
patch="http://dwm.suckless.org/patches/dwm-6.0-bstack.diff"
### END PKG INFO

if (( $UID == 0 )); then
   echo "Don't build as root, handsome."
   exit 1
fi

devel="quilt debian-keyring devscripts curl fakeroot libdistro-info-perl equivs"
sudo apt-get install "$devel"

prepare() {
   gpg -k # Initialize GPG config
   dget $source
   cd "$pkg-$ver"
   test -d debian/patches || mkdir -p debian/patches
   # https://bugs.debian.org/752624
   curl -Lo /tmp/099_meds.patch "$patch"
   quilt import /tmp/099_meds.patch
}

depends() {
   mk-build-deps
   sudo dpkg -i $pkg-build-deps*.deb
   sudo apt-get install -fy
}

build() {
   dch --local +nurse --distribution $dist "Just what the doctor ordered."
   dpkg-buildpackage -us -uc
}

# =====
prepare
# =====

case "$?" in
   0)
      depends && build
      ;;
   2)
      depends && build
      ;;
   *)
      echo "I couldn't cure you."
      exit 69
      ;;
esac

read -rp "Remove build dependencies? [y/n]" OPTION
case $OPTION in
   [yY])
      sudo apt-get autoremove --purge $pkg-build-deps
      ;;
   [nN])
      exit
      ;;
esac
