#!/bin/bash
# xfce4starter
#
# put last in ~/.xinitrc:
# exec xfce4starter run
#
# http://linuxbbq.org/bbs/viewtopic.php?f=15&t=1509
# https://wiki.archlinux.org/index.php/I3#Shutdown.2C_reboot.2C_lock_screen
# http://stackoverflow.com/questions/696839
# http://unix.stackexchange.com/questions/20370

XF1='xfsettingsd'
XF2='xfce4-panel'
XF3='xfdesktop'

xfce4_run() {
	if (( $UID == 0 )); then
		echo "XFCE4 should not be run as root."
		exit 1
	fi

	# quotes break arguments
	until $XF1 & do
		echo "$XF1 ended unexpectedly. Respawning.." >&2
		sleep 1
	done

	until $XF2 & do
		echo "$XF2 ended unexpectedly. Respawning.." >&2
		sleep 1
	done

	until $XF3 & do
		echo "$XF3 ended unexpectedly. Respawning.." >&2
		sleep 1
	done

	# only runs in foreground
	xfwm4
}

LOCK=i3lock-wrapper
WM_PID=$(xprop -id $(xprop -root _NET_SUPPORTING_WM_CHECK \
| awk -F'#' '{ print $2 }') _NET_WM_PID \
| awk -F' = ' '{ print $2 }')

# see man sudoers
case "$1" in
	run)
		xfce4_run
		;;
	lock)
		$LOCK
		;;
	exit)
		kill -15 $WM_PID
		;;
	suspend)
		sudo pm-suspend
		;;
	hibernate)
		sudo pm-hibernate
		;;
	reboot)
		sudo rc reboot
		;;
	shutdown)
		sudo rc shutdown
		;;
	*)
		echo "Usage: $0 {run|lock|exit|suspend|hibernate|reboot|shutdown}"
		exit 2
esac
