#!/bin/bash
# xfce4starter
#
# put last in ~/.xinitrc:
# exec xfce4starter run
#
# http://linuxbbq.org/bbs/viewtopic.php?f=15&t=1509
# https://wiki.archlinux.org/index.php/I3#Shutdown.2C_reboot.2C_lock_screen
# http://stackoverflow.com/questions/696839
# http://unix.stackexchange.com/questions/20370

xfce4_run() {
	xfsettingsd &
	xfce4-panel &
	xfdesktop &
	xfwm4
}

LOCK=i3lock-wrapper
WM_PID=$(xprop -id $(xprop -root _NET_SUPPORTING_WM_CHECK \
| awk -F'#' '{ print $2 }') _NET_WM_PID \
| awk -F' = ' '{ print $2 }')

# see man sudoers
case "$1" in
	run)
		xfce4_run
		;;
	lock)
		$LOCK
		;;
	exit)
		kill -15 $WM_PID
		;;
	suspend)
		$LOCK && sudo pm-suspend
		;;
	hibernate)
		$LOCK && sudo pm-hibernate
		;;
	reboot)
		sudo kill -2 1
		;;
	shutdown)
		sudo kill -10 1
		;;
	*)
		echo "Usage: $0 {run|lock|exit|suspend|hibernate|reboot|shutdown}"
		exit 2
esac
