#!/bin/bash
# xfce4starter
#
# "Magic process" - kill, session dies
# put last in ~/.xinitrc:
# exec xfce4starter run
#
# https://wiki.archlinux.org/index.php/I3#Shutdown.2C_reboot.2C_lock_screen
# http://linuxbbq.org/bbs/viewtopic.php?f=15&t=1509
# http://stackoverflow.com/questions/696839
# http://unix.stackexchange.com/questions/20370

xfce4_run() {
	if (( $UID == 0 )); then
		echo "Xfce should not be run as root."
		exit 1
	fi
	
	until xfsettingsd & do
		echo "xfsettingsd ended unexpectedly. Respawning.." >&2
		sleep 1
	done

	until xfce4-panel & do
		echo "xfce4-panel ended unexpectedly. Respawning.." >&2
		sleep 1
	done

	until xfdesktop & do
		echo "xfdesktop ended unexpectedly. Respawning.." >&2
		sleep 1
	done

	xfwm4
}

LOCK=i3lock-wrapper
WM_PID=$(xprop -id $(xprop -root _NET_SUPPORTING_WM_CHECK \
| awk -F'#' '{ print $2 }') _NET_WM_PID \
| awk -F' = ' '{ print $2 }')

case "$1" in
	run)
		xfce4_run
		;;
	lock)
		$LOCK
		;;
	exit)
		kill -15 $WM_PID
		;;
	suspend)
		sudo pm-suspend		# see man sudoers
		;;
	hibernate)
		sudo pm-hibernate
		;;
	reboot)
		sudo rc reboot
		;;
	shutdown)
		sudo rc shutdown
		;;
	*)
		echo "Usage: $0 {run|lock|exit|suspend|hibernate|reboot|shutdown}"
		exit 2
esac
